### ISSUE TITLE
[ISSUE] Lack of compatibility with OS versions previous to OS X 11.5

### ISSUE THREAD

**Issue by ajrdesign** [YoYoGames/GMEXT-Steamworks#19] opened 2023-04-05 18:19 UTC
I'm targeting OS 10.14 in my Xcode and on Gamemaker but players are reporting that the game won't open with 10.14 and it looks like they are getting errors saying this:

`Termination Reason:    DYLD, [0x4] Symbol missing
Dyld Error Message:
  Symbol not found: __ZNKSt3__14__fs10filesystem4path13__parent_pathEv
  Referenced from: /Users/USER/Library/Application [Support/Steam/*/power-of-ten.app/Contents/Resources/libsteamworks.dylib](https://steamcommunity.com/linkfilter/?url=http://Support/Steam/*/power-of-ten.app/Contents/Resources/libsteamworks.dylib) (which was built for Mac OS X 11.5)
  Expected in: /usr/lib/libc++.1.dylib`

To me it looks like libsteamworks.dylib isn't being built for the right OS. This could just be a steam thing but their documentation does say it [supports 10.11 and above](https://partner.steamgames.com/doc/store/application/platforms).

It's possible there's a configuration I'm missing so if so would love to know as I'd love to be able to solve this issue for my players. 

Here's [more context](https://steamcommunity.com/app/1319550/discussions/0/3821907263116806203/) and the players were nice enough to help out with some troubleshooting.

**Comment by DiasFranciscoA** [comment] 2023-06-20 20:47
Hello @ajrdesign, thank you for reaching out to us and for the detailed information you've provided. We understand the inconvenience this issue has caused and we appreciate your patience and your community's help in troubleshooting.

We have been investigating this issue and we believe we've identified the cause of the problem. It seems that there is a compatibility issue with some of the functions used by the extension, which seems to be causing issues on macOS versions older than 11.5.

We are currently working on a fix for this issue. Our aim is to ensure compatibility with macOS versions back to 10.15 in the upcoming updates of the extension.

We appreciate your patience and support while we work on a solution. Please keep an eye on the GitHub for the next update.

Thank you again for your support and understanding.

**Comment by DiasFranciscoA** [comment] 2023-07-19 09:14
Hello @ajrdesign,

Could you please confirm if the latest version of the extension, which has been released on both GitHub and the marketplace, has resolved the issue you previously encountered?

**Closed** 2023-07-21 08:52 UTC
