### ISSUE TITLE
"steam_input_get_digital_action_origins" example code returns white boxes

### ISSUE THREAD

**Issue by brettbubba03** [YoYoGames/GMEXT-Steamworks#73] opened 2024-06-10 14:26 UTC
![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/26512093/18fbb931-a238-40d4-a844-171e9f31e0fa)

The issue stems from the section in the for loop, where it adds the sprites, draws them, then deletes them. As it currently is, the sprites get turned into blank white boxes, but return to being the correct sprites when the sprite_delete() call is removed. Not sure what/where the issue is on this, but I'd wager its somewhere around there.

**Comment by brettbubba03** [comment] 2024-06-15 19:01
![image](https://github.com/YoYoGames/GMEXT-Steamworks/assets/26512093/9f40e73f-b6bc-4cdf-969e-751795b837db)
Just thought I should add that if I delete the temp sprites after the loop, it all works accordingly.

**Comment by jzavala-YYG** [comment] 2024-06-19 17:30
Hello @brettbubba03 I can't see the issue. Can you post a image?

**Comment by nkrapivin** [comment] 2024-06-24 10:25
Hi, I'm the guy behind the `steam_input_*` functions in this extension and I can't quite see the issue either. The individual icon sprites are drawn on to a temp surface, and then deleted, so it doesn't matter if they're deleted inside the loop as they'll be drawn on to the surface anyway, then the surface target is reset, the surface is turned into a sprite and the surface is then also deleted.
If you're required to store the sprite indicies inside the loop and delete them after, this sounds like a bug in the runtime.

**Comment by jzavala-YYG** [comment] 2024-06-24 19:02
If the issue isn't related to this extension I have to close this ticket. 

If you think an issue exists on the runner please create a new ticket with steps to replicate it.

Regards

**Closed by jzavala-YYG** 2024-06-24 19:02 UTC
Labels: Steamworks, extension
