### ISSUE TITLE
[FEATURE REQUEST] [DOCUMENTATION] Add support to get number of entries in Steam leaderboard

### ISSUE THREAD

**Issue by Dibbenator** [YoYoGames/GMEXT-Steamworks#28] opened 2023-08-15 22:01 UTC
### Is your feature request related to a problem?

I need to know how many entries there are in a Steam leaderboard due to the way I want to use the leaderboard.

The data is already downloaded from Steam within the API, but no function made available in the GameMaker API to retrieve it.

I have made my own working version of the function in a cloned version of the Gamemaker Steamworks repository and have a version of the sample Steamworks project. I just don't seem to have any way to push the change & couldn't see a way in GitHub how to request it. So I have added the code for the function in the solution description.

### Describe the solution you'd like

Code for steam_get_leaderboard_entry_count added to Steamworks API same or similar as the version I have working in my own clone of the API repository. Would like the function added so I don't have to add it every time new API is released.

//    \brief    Reports how many scores are available to download
YYEXPORT void /*double*/ steam_get_leaderboard_entry_count(RValue& Result, CInstance* selfinst, CInstance* otherinst, int argc, RValue* arg)//(const char* pszLeaderboardName, double startidx, double endidx)/*Steam_UserStats_DownloadScores*/
{
    const char* pszLeaderboardName = YYGetString(arg, 0);

    if (!steam_is_initialised)
    {
        // DebugConsoleOutput("Steam Initialisation failure\n");
        Result.kind = VALUE_REAL;
        Result.val = 0;
        return;
    }

    if (!SteamUser()->BLoggedOn())
    {
        DebugConsoleOutput("Get leaderboard entry count failed: must be logged on\n");
        Result.kind = VALUE_REAL;
        Result.val = -1;
        return; //=invalid async id
    }

    SteamLeaderboard_t hLeaderboard;
    if (GetLeaderboardHandle(pszLeaderboardName, hLeaderboard))
    {
        int numberofentries = SteamUserStats()->GetLeaderboardEntryCount(hLeaderboard);

        // DebugConsoleOutput("Number of entries downloaded %i\n", numberofentries);
 
        Result.kind = VALUE_REAL;
        Result.val = numberofentries;
    }
    else
    {
        DebugConsoleOutput("Leaderboard handler not available\n");
        Result.kind = VALUE_REAL;
        Result.val = 0;
    }
}

### Additional context

![SteamworksGM](https://github.com/YoYoGames/GameMaker-Feature-Requests/assets/24954931/8901a962-367c-4ada-860b-ebcd84ec8430)

**Comment by jzavala-YYG** [comment] 2024-01-12 19:58
@YYBartT 
https://partner.steamgames.com/doc/api/ISteamUserStats#GetLeaderboardEntryCount
steam_get_leaderboard_entry_count
/// @param {String} lb_name The name of the leaderboard
/// @returns {Real}

https://partner.steamgames.com/doc/api/ISteamUserStats#GetLeaderboardDisplayType
steam_get_leaderboard_display_type
/// @param {String} lb_name The name of the leaderboard
/// @returns {"constant bellow"}

https://partner.steamgames.com/doc/api/ISteamUserStats#ELeaderboardDisplayType
steam_display_type_none	0	This is only ever used when a leaderboard is invalid, you should never set this yourself.
steam_display_type_numeric	1	The score is just a simple numerical value.
steam_display_type_time_seconds	2	The score represents a time, in seconds.
steam_display_type_time_milliseconds	3	The score represents a time, in milliseconds.

**Comment by YYBartT** [comment] 2024-02-29 10:09
Added documentation for the functions listed above. The set of constants `steam_display_type_*` is a duplicate of the already existing set of constants `lb_sort_*`. Linked this existing constant as the return type of `steam_get_leaderboard_display_type`.

**Closed** 2024-03-01 14:52 UTC
Labels: feature-request, extension
